### ISSUE TITLE
Can not load the file locally.

### ISSUE THREAD

**Issue by St1pn** [ragavsachdeva/magi#3]
Background:
I have already downloaded the following model files from huggingface.co:
1.ragavsachdeva/magi
2.conditional-detr-resnet-50/
3.vit-mae-base/
4.trocr-base-printed/
They were all put under the same directory call Magi(Usage py file was also under this directory).
I have also modified the "_name_or_path"  in ocr_pretrained_processor_path, detection_model_config, crop_embedding_model_config in magi/config.json to "./conditional-detr-resnet-50", "./vit-mae-base", "./trocr-base-printed". ( I haven't modified the "_name_or_path" in our_model_config in magi/config.josn, which was originally set as "/work/rs/logs/manga_ocr/nt8rn2ul/". what does this param represent or mean?)

Problem:
when I tried to run the magi following the Usage part in the README file, I specified the model path in from_pretrained() as "./magi"I encountered this Warning:
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
and the py was still trying to get the model files from hugging face.co instead of loading the model locally (Raise huggingface_hub.utils._errors.LocalEntryNotFoundError)

Can you give a demo about how to load the file locally? (model files, location, parameter settings)

**Comment by ragavsachdeva** [comment]
Hi,

I am assuming you're able to perform inference using the provided example usage script, except you now want source code to be local on your machine.

I am afraid I can't spoon-feed you how to achieve what you're trying to do, but here is what I recommend. Start simple. Rather than downloading ragavsachdeva/magi + conditional-detr-resnet-50 + vit-mae-base + trocr-base-printed into a single folder, do this instead: 
- Make a new folder called `project`.
- Inside `project` make a fresh clone of `ragavsachdeva/magi` (including the model weights). This folder, i.e. `project/magi`, should should have the same files as [here](https://huggingface.co/ragavsachdeva/magi/tree/main). 
- Next, inside `project` (**not** inside `project/magi`) create a `inference.py` script (as in the readme). Change the script to load the model locally as `model = AutoModel.from_pretrained("./magi")`
- Finally, run `inference.py`. This should work, and in fact run from the local copy of the code. You can verify this by adding print statements inside `project/magi/modelling_magi.py` file.

Note that even though this should run from the local source files, they still have dependencies and imports from the `transformers` library. So you'll see this warning for example:

> Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.

which comes from [this from_pretrained](https://huggingface.co/ragavsachdeva/magi/blob/2031a4315111748726e2abda9f131d998c789a09/processing_magi.py#L20) call in the processor. Similarly, [this line](https://huggingface.co/ragavsachdeva/magi/blob/2031a4315111748726e2abda9f131d998c789a09/modelling_magi.py#L26) will instantiate the ViTMAE model by making a call to the transformers library. If you want to have the source files for all these models locally, you'll need to incrementally make local copies of their modelling files from HF transformers and correctly update all the imports.

Regarding, "/work/rs/logs/manga_ocr/nt8rn2ul/", it does nothing anymore (I've now updated the config to remove this path with another dummy placeholder).

**Comment by bobinwobbin** [comment]
Hey,

I'm currenlty trying to get magiv2 to run locally and saw this post and tested out your advice. If I simply try that, it raises an import error:

raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: utils, configuration_magiv2, processing_magiv2. Run `pip install utils configuration_magiv2 processing_magiv2` 

Since the inference script isn't in the same place as these scripts, it's not working. I tried to literally just copy paste the neccessary files outside the actual folder as well so that my inference script would atleast not get an import error but then I get this error:

Traceback (most recent call last):
  File "c:\Users\Neu\Downloads\test\inference.py", line 6, in <module>
    model = AutoModel.from_pretrained("./magiv2", trust_remote_code=True).eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Neu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\auto_factory.py", line 557, in from_pretrained
    cls.register(config.__class__, model_class, exist_ok=True)
  File "C:\Users\Neu\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\auto_factory.py", line 584, in register
    raise ValueError(
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'configuration_magiv2.Magiv2Config'> and you passed <class 'transformers_modules.magiv2.configuration_magiv2.Magiv2Config'>. Fix one of those so they match!

I honestly don't have much knowledge on this topic, so any help would be greatly appreciated
